server:
  port: 8087
  servlet:
    context-path: /bootservice

spring:
  application:
    name: boot_service
  redis:
    host: 47.117.128.180
    password: 123456
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.117.128.180:3306/user_manage?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: usermanage
    password: 12345678

mybatis:
  mapper-locations: classpath*:config/mybatis/mappers/mysql/**/*.xml
  config-location: classpath:config/mybatis/config/mysql/mybatis-config.xml

knife4j:
  enable: true
  setting:
    enableDocumentManage: true

upload-path: C:/root/cxtx/image

